#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from src.contracts.video import (  # noqa: E402
    FULL_EDIT_MODEL_IDS,
    PATCH_EDIT_MODEL_IDS,
    VIDEO_MODE_IDS,
    VIDEO_MODEL_IDS,
)


def _ts_array(name: str, values: tuple[str, ...]) -> str:
    joined = ",\n  ".join(f'"{value}"' for value in values)
    return f"export const {name} = [\n  {joined},\n] as const;\n"


def main() -> None:
    output = ROOT / "frontend" / "src" / "lib" / "generated" / "videoContracts.ts"
    header = "// Generated by scripts/sync_video_contracts.py. Do not edit manually.\n\n"
    body = "".join(
        [
            _ts_array("VIDEO_MODEL_IDS", VIDEO_MODEL_IDS),
            "\n",
            _ts_array("VIDEO_MODE_IDS", VIDEO_MODE_IDS),
            "\n",
            _ts_array("FULL_EDIT_MODEL_IDS", FULL_EDIT_MODEL_IDS),
            "\n",
            _ts_array("PATCH_EDIT_MODEL_IDS", PATCH_EDIT_MODEL_IDS),
            "\n",
            "export type VideoModelId = (typeof VIDEO_MODEL_IDS)[number];\n",
            "export type VideoModeId = (typeof VIDEO_MODE_IDS)[number];\n",
            "export type FullEditModelId = (typeof FULL_EDIT_MODEL_IDS)[number];\n",
            "export type PatchEditModelId = (typeof PATCH_EDIT_MODEL_IDS)[number];\n",
        ]
    )
    output.write_text(header + body, encoding="utf-8")


if __name__ == "__main__":
    main()
