#!/usr/bin/env python3
from __future__ import annotations

import sys
import types
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin, get_type_hints
from typing_extensions import NotRequired, Required, TypedDict

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from src.contracts.api import (  # noqa: E402
    ASSET_DELETE_TYPE_IDS,
    ASSET_UPLOAD_TYPE_IDS,
    CUSTOM_REPORT_OUTPUT_ASSET_TYPE_IDS,
    CUSTOM_REPORT_TYPE_IDS,
    JOB_STATUS_IDS,
    MANUAL_REFINE_EXPORT_FORMAT_IDS,
    QC_EDGE_BIAS_IDS,
    QC_EDGE_SUPPRESSION_IDS,
    QC_SAM_PROMPT_TYPE_IDS,
    SEGMENT_CROP_ASPECT_IDS,
    TASK_STATUS_IDS,
    TOPAZ_UPSCALE_PRESET_IDS,
    TOPAZ_VIDEO_MODEL_IDS,
    ApiAssetUploadInitPayload,
    ApiImageEditFullPayload,
    ApiImageEditPatchPayload,
    ApiReferenceVideoGeneratePayload,
    AssetDeletePayload,
    ChunkedSegmentGeneratePayload,
    CropEdgeFeatherPayload,
    CustomReportCreatePayload,
    CustomReportOutputRefPayload,
    ExportTopazUpscalePayload,
    MergeGenerationAdjustmentPayload,
    MergePayload,
    PatchRectPayload,
    ReconcileTimingPayload,
    SegmentGenerationLengthenPayload,
    SegmentGenerationExtendPayload,
    SegmentGeneratePayload,
)
from src.contracts.video import (  # noqa: E402
    FULL_EDIT_MODEL_IDS,
    HAPPY_HORSE_RESOLUTION_IDS,
    PATCH_EDIT_MODEL_IDS,
    REPLICATE_KLING_MODE_IDS,
    REPLICATE_KLING_V3_MODE_IDS,
    SORA2_RESOLUTION_IDS,
    VIDEO_MODE_IDS,
    VIDEO_MODEL_IDS,
    WAN27_RESOLUTION_IDS,
)


def _ts_array(name: str, values: tuple[str, ...]) -> str:
    joined = ",\n  ".join(f'"{value}"' for value in values)
    return f"export const {name} = [\n  {joined},\n] as const;\n"


def _ts_literal(value: Any) -> str:
    if isinstance(value, str):
        return f'"{value}"'
    if value is None:
        return "null"
    return str(value)


def _annotation_to_ts(annotation: Any) -> str:
    origin = get_origin(annotation)

    if origin in {NotRequired, Required}:
        return _annotation_to_ts(get_args(annotation)[0])

    if origin is Literal:
        return " | ".join(_ts_literal(value) for value in get_args(annotation))

    if origin in {list, tuple}:
        args = get_args(annotation)
        item = _annotation_to_ts(args[0]) if args else "unknown"
        return f"{item}[]"

    if origin is dict:
        args = get_args(annotation)
        key = _annotation_to_ts(args[0]) if len(args) > 0 else "string"
        value = _annotation_to_ts(args[1]) if len(args) > 1 else "unknown"
        if key != "string":
            key = "string"
        return f"Record<{key}, {value}>"

    if origin in {types.UnionType, Union}:
        return " | ".join(_annotation_to_ts(arg) for arg in get_args(annotation))

    if annotation is str:
        return "string"
    if annotation in {int, float}:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is type(None):
        return "null"
    if annotation is Any:
        return "unknown"

    if isinstance(annotation, type) and hasattr(annotation, "__annotations__") and hasattr(annotation, "__total__"):
        return annotation.__name__

    return "unknown"


def _typed_dict_to_ts(name: str, model: type[TypedDict]) -> str:
    annotations = get_type_hints(model, include_extras=True)
    required_keys = set(getattr(model, "__required_keys__", set()))
    fields: list[str] = []
    for field_name, annotation in annotations.items():
        optional = "" if field_name in required_keys else "?"
        fields.append(f"  {field_name}{optional}: {_annotation_to_ts(annotation)};")
    body = "\n".join(fields)
    return f"export type {name} = {{\n{body}\n}};\n"


def _write_video_contracts() -> None:
    output = ROOT / "frontend" / "src" / "lib" / "generated" / "videoContracts.ts"
    header = "// Generated by scripts/sync_video_contracts.py. Do not edit manually.\n\n"
    body = "".join(
        [
            _ts_array("VIDEO_MODEL_IDS", VIDEO_MODEL_IDS),
            "\n",
            _ts_array("VIDEO_MODE_IDS", VIDEO_MODE_IDS),
            "\n",
            _ts_array("FULL_EDIT_MODEL_IDS", FULL_EDIT_MODEL_IDS),
            "\n",
            _ts_array("PATCH_EDIT_MODEL_IDS", PATCH_EDIT_MODEL_IDS),
            "\n",
            _ts_array("REPLICATE_KLING_MODE_IDS", REPLICATE_KLING_MODE_IDS),
            "\n",
            _ts_array("REPLICATE_KLING_V3_MODE_IDS", REPLICATE_KLING_V3_MODE_IDS),
            "\n",
            _ts_array("WAN27_RESOLUTION_IDS", WAN27_RESOLUTION_IDS),
            "\n",
            _ts_array("HAPPY_HORSE_RESOLUTION_IDS", HAPPY_HORSE_RESOLUTION_IDS),
            "\n",
            _ts_array("SORA2_RESOLUTION_IDS", SORA2_RESOLUTION_IDS),
            "\n",
            "export type VideoModelId = (typeof VIDEO_MODEL_IDS)[number];\n",
            "export type VideoModeId = (typeof VIDEO_MODE_IDS)[number];\n",
            "export type FullEditModelId = (typeof FULL_EDIT_MODEL_IDS)[number];\n",
            "export type PatchEditModelId = (typeof PATCH_EDIT_MODEL_IDS)[number];\n",
            "export type ReplicateKlingModeId = (typeof REPLICATE_KLING_MODE_IDS)[number];\n",
            "export type ReplicateKlingV3ModeId = (typeof REPLICATE_KLING_V3_MODE_IDS)[number];\n",
            "export type Wan27ResolutionId = (typeof WAN27_RESOLUTION_IDS)[number];\n",
            "export type HappyHorseResolutionId = (typeof HAPPY_HORSE_RESOLUTION_IDS)[number];\n",
            "export type Sora2ResolutionId = (typeof SORA2_RESOLUTION_IDS)[number];\n",
        ]
    )
    output.write_text(header + body, encoding="utf-8")


def _write_api_contracts() -> None:
    output = ROOT / "frontend" / "src" / "lib" / "generated" / "apiContracts.ts"
    header = "// Generated by scripts/sync_video_contracts.py. Do not edit manually.\n\n"
    constants = "".join(
        [
            _ts_array("TASK_STATUS_IDS", TASK_STATUS_IDS),
            "\n",
            _ts_array("JOB_STATUS_IDS", JOB_STATUS_IDS),
            "\n",
            _ts_array("ASSET_UPLOAD_TYPE_IDS", ASSET_UPLOAD_TYPE_IDS),
            "\n",
            _ts_array("SEGMENT_CROP_ASPECT_IDS", SEGMENT_CROP_ASPECT_IDS),
            "\n",
            _ts_array("ASSET_DELETE_TYPE_IDS", ASSET_DELETE_TYPE_IDS),
            "\n",
            _ts_array("CUSTOM_REPORT_OUTPUT_ASSET_TYPE_IDS", CUSTOM_REPORT_OUTPUT_ASSET_TYPE_IDS),
            "\n",
            _ts_array("CUSTOM_REPORT_TYPE_IDS", CUSTOM_REPORT_TYPE_IDS),
            "\n",
            _ts_array("MANUAL_REFINE_EXPORT_FORMAT_IDS", MANUAL_REFINE_EXPORT_FORMAT_IDS),
            "\n",
            _ts_array("QC_EDGE_SUPPRESSION_IDS", QC_EDGE_SUPPRESSION_IDS),
            "\n",
            _ts_array("QC_SAM_PROMPT_TYPE_IDS", QC_SAM_PROMPT_TYPE_IDS),
            "\n",
            _ts_array("QC_EDGE_BIAS_IDS", QC_EDGE_BIAS_IDS),
            "\n",
            _ts_array("TOPAZ_VIDEO_MODEL_IDS", TOPAZ_VIDEO_MODEL_IDS),
            "\n",
            _ts_array("TOPAZ_UPSCALE_PRESET_IDS", TOPAZ_UPSCALE_PRESET_IDS),
            "\n",
            "export type TaskStatusId = (typeof TASK_STATUS_IDS)[number];\n",
            "export type JobStatusId = (typeof JOB_STATUS_IDS)[number];\n",
            "export type AssetUploadTypeId = (typeof ASSET_UPLOAD_TYPE_IDS)[number];\n",
            "export type SegmentCropAspectId = (typeof SEGMENT_CROP_ASPECT_IDS)[number];\n",
            "export type AssetDeleteTypeId = (typeof ASSET_DELETE_TYPE_IDS)[number];\n",
            "export type CustomReportOutputAssetTypeId = (typeof CUSTOM_REPORT_OUTPUT_ASSET_TYPE_IDS)[number];\n",
            "export type CustomReportTypeId = (typeof CUSTOM_REPORT_TYPE_IDS)[number];\n",
            "export type ManualRefineExportFormatId = (typeof MANUAL_REFINE_EXPORT_FORMAT_IDS)[number];\n",
            "export type QcEdgeSuppressionId = (typeof QC_EDGE_SUPPRESSION_IDS)[number];\n",
            "export type QcSamPromptTypeId = (typeof QC_SAM_PROMPT_TYPE_IDS)[number];\n",
            "export type QcEdgeBiasId = (typeof QC_EDGE_BIAS_IDS)[number];\n\n",
            "export type TopazVideoModelId = (typeof TOPAZ_VIDEO_MODEL_IDS)[number];\n",
            "export type TopazUpscalePresetId = (typeof TOPAZ_UPSCALE_PRESET_IDS)[number];\n\n",
        ]
    )

    typed_dict_models: list[tuple[str, type[TypedDict]]] = [
        ("PatchRectPayload", PatchRectPayload),
        ("SegmentGeneratePayload", SegmentGeneratePayload),
        ("ChunkedSegmentGeneratePayload", ChunkedSegmentGeneratePayload),
        ("SegmentGenerationExtendPayload", SegmentGenerationExtendPayload),
        ("SegmentGenerationLengthenPayload", SegmentGenerationLengthenPayload),
        ("ReconcileTimingPayload", ReconcileTimingPayload),
        ("CropEdgeFeatherPayload", CropEdgeFeatherPayload),
        ("MergeGenerationAdjustmentPayload", MergeGenerationAdjustmentPayload),
        ("MergePayload", MergePayload),
        ("ApiAssetUploadInitPayload", ApiAssetUploadInitPayload),
        ("ApiImageEditFullPayload", ApiImageEditFullPayload),
        ("ApiImageEditPatchPayload", ApiImageEditPatchPayload),
        ("ApiReferenceVideoGeneratePayload", ApiReferenceVideoGeneratePayload),
        ("AssetDeletePayload", AssetDeletePayload),
        ("ExportTopazUpscalePayload", ExportTopazUpscalePayload),
        ("CustomReportOutputRefPayload", CustomReportOutputRefPayload),
        ("CustomReportCreatePayload", CustomReportCreatePayload),
    ]
    typed_defs = "\n".join(_typed_dict_to_ts(name, model) for name, model in typed_dict_models)
    output.write_text(header + constants + typed_defs, encoding="utf-8")


def main() -> None:
    _write_video_contracts()
    _write_api_contracts()


if __name__ == "__main__":
    main()
